# Generated by Django 5.0.6 on 2024-06-21 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0006_alter_resolution_title_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolution',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('progress', models.TextField()),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.resolution')),
            ],
        ),
    ]
