# Generated by Django 5.0.6 on 2024-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0007_resolution_end_date_resolution_start_date_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='resolution',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
