# Generated by Django 5.0.6 on 2024-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0008_remove_resolution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='completed_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resolution',
            name='total_steps',
            field=models.IntegerField(default=100),
        ),
    ]
